spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/task-1
    username: postgres
    password: 2100401
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect